query CheckRunAnnotations($id: ID!, $cursor: String) {
  _shepherdRateLimit: rateLimit {
    cost
    limit
    nodeCount
    remaining
    resetAt
    used
  }
  node(id: $id) {
    __typename
    ... on CheckRun {
      annotations(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          fullDatabaseId
          path
          annotationLevel
          title
          message
          rawDetails
          blobUrl
          location {
            start {
              line
              column
            }
            end {
              line
              column
            }
          }
        }
      }
    }
  }
}
