mutation CreateCommitOnBranch(
  $repoWithOwner: String!
  $branch: String!
  $expectedHeadOid: GitObjectID!
  $message: CommitMessage!
  $additions: [FileAddition!]
) {
  createCommitOnBranch(
    input: {
      branch: { repositoryNameWithOwner: $repoWithOwner, branchName: $branch }
      expectedHeadOid: $expectedHeadOid
      message: $message
      fileChanges: { additions: $additions }
    }
  ) {
    commit {
      oid
      url
    }
  }
}
