mutation MinimizeComment($commentId: ID!, $classifier: ReportedContentClassifiers!) {
  minimizeComment(input: { subjectId: $commentId, classifier: $classifier }) {
    minimizedComment {
      isMinimized
    }
  }
}
