fragment PollSummaryCheckContexts on StatusCheckRollupContextConnection {
  totalCount
  pageInfo {
    hasPreviousPage
    startCursor
  }
  nodes {
    __typename
    ... on CheckRun {
      id
      name
      status
      conclusion
      detailsUrl
      checkSuite {
        workflowRun {
          databaseId
          event
          workflow {
            databaseId
            name
          }
        }
      }
    }
    ... on StatusContext {
      context
      state
    }
  }
}
