fragment PollSummaryPr on PullRequest {
  number
  title
  url
  state
  updatedAt
  isDraft
  viewerCanUpdate
  headRefName
  headRefOid
  baseRefName
  baseRefOid
  mergeable
  mergeStateStatus
  lifecycleEvents: timelineItems(
    last: 1
    itemTypes: [CLOSED_EVENT, REOPENED_EVENT, CONVERT_TO_DRAFT_EVENT, READY_FOR_REVIEW_EVENT]
  ) {
    nodes {
      __typename
      ... on ClosedEvent {
        createdAt
      }
      ... on ReopenedEvent {
        createdAt
      }
      ... on ConvertToDraftEvent {
        createdAt
      }
      ... on ReadyForReviewEvent {
        createdAt
      }
    }
  }
  reviewDecision
  reviewRequests(last: 50) {
    nodes {
      requestedReviewer {
        __typename
        ... on User {
          login
        }
        ... on Bot {
          login
        }
        ... on Mannequin {
          login
        }
      }
    }
  }
  latestReviews(last: 50) {
    nodes {
      state
      author {
        __typename
        login
      }
    }
  }
  isInMergeQueue
  mergeQueueAdditions: timelineItems(last: 1, itemTypes: [ADDED_TO_MERGE_QUEUE_EVENT]) {
    nodes {
      ... on AddedToMergeQueueEvent {
        createdAt
      }
    }
  }
  mergeQueueRemovals: timelineItems(last: 1, itemTypes: [REMOVED_FROM_MERGE_QUEUE_EVENT]) {
    nodes {
      ... on RemovedFromMergeQueueEvent {
        id
        reason
        createdAt
        actor {
          login
        }
        beforeCommit {
          oid
          parents(first: 100) {
            nodes {
              oid
            }
          }
        }
      }
    }
  }
  mergeQueueEntry {
    headCommit {
      oid
      statusCheckRollup {
        contexts(last: 100) {
          ...PollSummaryCheckContexts
        }
      }
    }
  }
  stack {
    number
    size
    baseRefName
  }
  stackEntry {
    position
  }
  comments(last: 100) {
    totalCount
    pageInfo {
      hasPreviousPage
    }
    nodes {
      id
      body
      isMinimized
      url
      authorAssociation
      author {
        __typename
        login
      }
    }
  }
  reviews(last: 100) {
    totalCount
    pageInfo {
      hasPreviousPage
    }
    nodes {
      id
      body
      state
      isMinimized
      authorAssociation
      author {
        __typename
        login
      }
    }
  }
  reviewThreads(last: 20) {
    totalCount
    pageInfo {
      hasPreviousPage
    }
    nodes {
      id
      isResolved
      isOutdated
      path
      rootComments: comments(first: 1) {
        nodes {
          id
          body
          url
          viewerDidAuthor
          authorAssociation
          author {
            __typename
            login
          }
        }
      }
      comments(last: 5) {
        totalCount
        pageInfo {
          hasPreviousPage
        }
        nodes {
          id
          body
          url
          authorAssociation
          viewerDidAuthor
          author {
            __typename
            login
          }
        }
      }
    }
  }
  commits(last: 1) {
    nodes {
      commit {
        oid
        committedDate
        statusCheckRollup {
          contexts(last: 100) {
            ...PollSummaryCheckContexts
          }
        }
      }
    }
  }
}
