query SuggestionThreads($owner: String!, $repo: String!, $pr: Int!, $threadIds: [ID!]!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $pr) {
      headRefOid
      headRefName
      headRepository {
        nameWithOwner
      }
    }
  }
  nodes(ids: $threadIds) {
    ... on PullRequestReviewThread {
      id
      isResolved
      isOutdated
      path
      line
      startLine
      pullRequest {
        number
      }
      comments(first: 1) {
        nodes {
          isMinimized
          url
          authorAssociation
          author {
            __typename
            login
          }
          body
          path
          line
          startLine
          createdAt
        }
      }
    }
  }
}
